name: TruffleHog Scan

on:
  push:
  pull_request:

jobs:
  call-trufflehog:
    uses: ./.github/workflows/trufflehog.yml
    with:
      working-directory: "."
      fail-on-secrets: true
      upload-artifact: true
      scan-issues-prs: true
      trufflehog-ignore-patterns: ""
