name: TruffleHog Secret Scan

permissions:
  contents: read
  issues: read
  pull-requests: read

on:
  push:
  pull_request:

jobs:
  call-trufflehog:
    uses: mahekshahbad/trufflehog-secret-scanning/.github/workflows/trufflehog.yml@main
    with:
      working-directory: "."
      fail-on-secrets: true
      upload-artifact: true
      scan-issues-prs: true
      trufflehog-ignore-patterns: ""
